Update agenda for meetup 8 and 9
aicoe-aiops/operate-first-data-science-community pull request #71
Opened 2022-03-24 22:47 UTC by aakankshaduggal

This PR updates agenda for meetup 8 (#51) and meetup 9(#46). It also updates the agenda for the previous meetups' slides

2022-03-24 22:47 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aakankshaduggal** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Foperate-first-data-science-community).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/aicoe-aiops/operate-first-data-science-community/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["aakankshaduggal"]} -->

2022-03-24 23:15 UTC, oindrillac requested changes

2022-03-24 23:15 UTC, oindrillac commented on docs/content.md
> +
Can we add something like
```suggestion
In this session, attendees learn about a set of AIOps services deployed on Operate First that they can start using and get familiarized with how to use the set of tools available on the Operate First cloud to deploy their own workloads . 
```

2022-03-24 23:20 UTC, oindrillac commented on docs/content.md
>  **Sandiego**
nit - formatting for this session is different from others. Date and title are on different lines/

2022-03-24 23:22 UTC, oindrillac commented on docs/content.md
>  **Sandiego**
nit: formatting for title and date for this session is different from others. should be on same line?

2022-03-24 23:22 UTC, oindrillac requested changes
small nit, otherwise lgtm

2022-03-25 00:39 UTC, aakankshaduggal commented
Thanks for the review @oindrillac , fixed it :+1:

2022-03-25 15:04 UTC, oindrillac approved these changes
/lgtm
/approve

2022-03-25 15:04 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aicoe-aiops/operate-first-data-science-community/pull/71#pullrequestreview-921773850" title="Approved">oindrillac</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **aakankshaduggal** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Foperate-first-data-science-community).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/aicoe-aiops/operate-first-data-science-community/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["aakankshaduggal"]} -->

2022-03-25 15:29 UTC, MichaelClifford commented
/approve

2022-03-25 15:29 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aicoe-aiops/operate-first-data-science-community/pull/71#issuecomment-1079142150" title="Approved">MichaelClifford</a>*, *<a href="https://github.com/aicoe-aiops/operate-first-data-science-community/pull/71#pullrequestreview-921773850" title="Approved">oindrillac</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Foperate-first-data-science-community).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aicoe-aiops/operate-first-data-science-community/blob/main/OWNERS)~~ [MichaelClifford]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-25 15:32 UTC, merged